tabWidth: 2
printWidth: 100
singleQuote: false
trailingComma: none
semi: true
bracketSpacing: true
jsxsingleQuote: false
endOfLine: lf
arrowParens: avoid
parser:
  - typescript
  - graphql
  - css
  - scss
  - json
  - json-stringify
  - html
  - yaml
